metric_names: ['Cosine Similarity']
# p_vals: [0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1]
p_vals: [0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1]
model_weight_types: ['weight', 'bias']
model_layer_names: ['grad_layers.0', 'grad_output_layer']
dataset_name: 'mnist_split'
grad_type_arr: ['past']
memory_method_arr: ['iCaRL']
num_tasks: 5
num_ideal_models: 10
num_runs: 10